name: Run unit tests

on:
  push:
    branches: [master]
    paths:
      - 'pnpm-lock.yaml'
      - 'packages/**'
  pull_request:
    branches: [master]
    paths:
      - 'pnpm-lock.yaml'
      - 'packages/**'

jobs:
  test:
    name: "Unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: "Checking-out code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          submodules: false

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
        with:
          version: 10

      - name: "Defining node version"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: 'pnpm'

      - name: "Installing dependencies"
        run: pnpm install

      - name: "Running unit tests"
        run: pnpm -r test

      - name: "Linting packages"
        working-directory: ./packages/generator-widget
        run: pnpm -r lint
